"""empty message

Revision ID: 33419d02575b
Revises: 
Create Date: 2023-11-08 17:25:11.698632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33419d02575b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('act_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_firstname', sa.String(length=25), nullable=False),
    sa.Column('act_lastname', sa.String(length=25), nullable=False),
    sa.Column('act_language', sa.String(length=2), nullable=True),
    sa.Column('act_gender', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('act_id')
    )
    op.create_table('movies',
    sa.Column('mov_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mov_title', sa.String(length=30), nullable=False),
    sa.Column('mov_release', sa.Integer(), nullable=True),
    sa.Column('mov_language', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('mov_id'),
    sa.UniqueConstraint('mov_id', 'mov_title', 'mov_release')
    )
    op.create_table('casts',
    sa.Column('cas_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mov_id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('cas_role', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['actors.act_id'], ),
    sa.ForeignKeyConstraint(['mov_id'], ['movies.mov_id'], ),
    sa.PrimaryKeyConstraint('cas_id'),
    sa.UniqueConstraint('mov_id', 'act_id', 'cas_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('casts')
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
